### ISSUE TITLE
**IDEA** Adding Wind Gust and others

### ISSUE THREAD

**Issue by ebarretopr** [MarcoGos/davis_vantage#1]
It has been working fine for me for the last day. Wondering if Wind Gust along with Hi or Lows for the day could be added?

**Comment by MarcoGos** [comment]
Good idea, I will see what I can do.

**Comment by dz4news** [comment]
Wind Gusts would be great. I was adding to home assistant and wind gusts would be a nice addition to my weather page. Woking great with a Vantage Vue.. thanks for the work on this.

**Comment by MarcoGos** [comment]
Added the wind gust and high/low values incl. the high/low value times in v1.1.0.
