### ISSUE TITLE
During installation I am not asked for network port and/or IP

### ISSUE THREAD

**Issue by fft1010** [MarcoGos/davis_vantage#12]
HI,
I the configuration via HACS like described here:
http://homeassistant.local:8123/hacs/repository/698694783
The it says: 
```
During the setup of the integration the serial port or the hostname of the weather station needs to be provided.
Example network host: 192.168.0.18:22222
```
which I am never asked. (de-installed it now twice and re-installed. I have 2024.8.1 running (check with the version 7.3 before with the same result.)

Can someone give me a hint, where I find the config file on my system an add the needed informations manually?

thanks
Juergen

**Comment by MarcoGos** [comment]
Hi @fft1010 , during the installation of the Davis Integration the first page you see is Protocol. You see the options "Serial" and "Network". Choose "Netork" and click on Submit. After that a page with "Host" will be shown. Enter the host like you saw in the example and Submit again.

**Comment by fft1010** [comment]
Hi @MarcoGos ,
I now deleted it 3 more times, but without success  to get any config page. Here is what I do:
1.) HACS on the left of my HA
2.) Klick on it, put "davis" in ther search, and klick on the "Davis Vantage" 
![screen-2024-08-16-16-44-56](https://github.com/user-attachments/assets/d5586630-b888-4055-b061-66dcc852fa5c)
3.) Klick on it and than klick on the "Download" button in the lower right. Message says: Download goes to '/config/custom_components/davis_vantage' and I have to restart HA. Klick on "Download".
4.) After download I get 
![screen-2024-08-16-16-46-39](https://github.com/user-attachments/assets/b310974d-c063-4484-85f7-0dcfd304135b)
and klick on that -> HA is restarting.
5.) ... and than? ARGH..... never did
6.) Setup, Integrations -> add integration button lower right. Sorry. All other configs until now pop up and ask for configuration, I was waiting for this.

**Comment by fft1010** [comment]
Hi,
now the setup comes, I can give the IP and use the port, but there is not connection. I have another integration done of my own, which I get data from at
`http://192.168.90.146/v1/current_conditions`

So I assumed

http://192.168.90.146:22222

would be correct. But I only get the red warning afterwards.

any idea?
thanks
Jeurgen

**Comment by MarcoGos** [comment]
What kind of device are you using?
