### ISSUE TITLE
High CPU when pulling data + minor translation spelling.

### ISSUE THREAD

**Issue by MarkHofmann11** [MarcoGos/davis_vantage#13]
1)  English "Temperature (Inside)" vs "Temperatuu (Inside)".
LINE 68 - 
            "temperature_inside": {
                "name": "Temperatuur (Inside)"

2)  There might be no solution, but I noticed high CPU spikes in HA when polling the Davis Vantage Pro Wireless 2.  Using Glances on the VM, right when the last poll happens the CPU spikes to near 100% (python3 process).  With the component disabled, I don't see the spike.  

I am polling a Davis Vantage Pro2 Wireless - using Virtual VP 1.2.5 via IP (IP address + port) in this case of port 5513.

Everything is working 100% and really want to thank you for making this great custom component for Davis Weather Stations for HA!

**Comment by MarcoGos** [comment]
FIxed typo via version 1.2.3
