### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yestrdave** [MarcoGos/davis_vantage#14]
I was considering purchasing Vantage Vue Weather Station with WeatherLink Console - SKU 6242, 6242M. Has anyone confirmed it will work yet.  The Davis stuff looks like a great product but I really want it to work local.   Sorry I put this under issues.

**Comment by MarcoGos** [comment]
Hi @yestrdave , I don't think the new weatherlink console will work together with this integration. There is however another home assistant integration (also via HACS) called WeatherLink, which reads the information from the weatherlink cloud service. Maybe you can use that.

**Comment by yestrdave** [comment]
Thank you. I ordered one yesterday.   I really don’t want something that uses the only the cloud. As specially one I have to pay for.  Is this something you can modify to work?

Thanks DaveR
________________________________

**Comment by MarcoGos** [comment]
@yestrdave Unfortunately not. This integration will only work on older version of weatherlink devices.

**Comment by yestrdave** [comment]
Thank you.  I’ll change directions.

Thanks DaveR
________________________________
