### ISSUE TITLE
Archive data interval

### ISSUE THREAD

**Issue by matthewjreeves** [MarcoGos/davis_vantage#15]
Hi, firstly, this integration is excellent. Thanks for putting in all the time and effort!
My archive data interval seems to be sitting at 30 mins according to the diagnostic entity. Do you know if it's possible to change that to 5 or 10 minutes?
I am running a vantage pro 2 with weatherlink IP.

Thanks!

**Comment by MarcoGos** [comment]
Hi @matthewjreeves , you can change the archive interval by using the original WeatherLink software.

**Comment by matthewjreeves** [comment]
Sorted. Thanks
