### ISSUE TITLE
Integration will not load

### ISSUE THREAD

**Issue by dz4news** [MarcoGos/davis_vantage#3]
I have updated to the latest version of HA and now I can not get the Davis_Vantage intergration to load. I get this error {"message":"Invalid handler specified"} after the integration attempts to load. I have tried the latest release and tried to revert back to an older version of the integration, but always get the same error message. Any ideas?

**Comment by dz4news** [comment]
This is what my home assistant logs show...

Logger: homeassistant.config_entries
Source: config_entries.py:2077
First occurred: 9:22:10 PM (2 occurrences)
Last logged: 9:22:19 PM

Error occurred loading flow for integration davis_vantage: No module named 'pylink'

**Comment by MarcoGos** [comment]
I will look into this problem asap.

**Comment by MarcoGos** [comment]
Fixed in v1.1.4
