### ISSUE TITLE
Latest Update - error logs

### ISSUE THREAD

**Issue by dz4news** [MarcoGos/davis_vantage#4]
Since the latest version (v1.11.1) , I get the following errors in my HA log file.

This error originated from a custom integration.

Logger: pyvpdriver
Source: custom_components/davis_vantage/client.py:90
Integration: Davis Vantage (documentation, issues)
First occurred: 8:58:35 PM (1 occurrences)
Last logged: 8:58:35 PM

Check ACK: BAD ('\n\r' != '')

**Comment by MarcoGos** [comment]
This error will popup now and then due to the weatherstation itself. Nothing to worry about.
