### ISSUE TITLE
Not compatible with Weatherdisplay

### ISSUE THREAD

**Issue by vk2him** [MarcoGos/davis_vantage#7]
Just advising that I've noticed a conflict with this integration and Weatherdisplay program for PC.

My Vantage Pro2  has an IP datalogger and for the last 15 years it's been working fine with Weatherdisplay.

After installing this integration, I noticed that Weatherdisplay would occasionally "miss" seeing the bucket tips, so the Weatherdisplay rain reading were always lower than what was displayed on the Pro2 console.

I worked out that the IP datalogger doesn't like talking to multiple IP destinations - it seems to bind to one IP (such as this integration), and when that happens any other IP destination (such as Weather display) won't see the data. The IP logger then binds to the other destination and teh other one misses.

I've disabled the integration and Weatherdisplay is back to being in sync with the consol when it's raining. Other weather elements may also be affected in a similar way, however Weatherdisplay seems to rely on counting the actual number of bucket tips rather than reading the daily/monthly/yearly rain totals.

Other than that issue, the integration was working fine. I'm unsure if this can be fixed as it seems to be a shortcoming of the IP logger.

**Comment by MarcoGos** [comment]
As you've already noticed the IP logger cannot provide information to two or more applications at once. It's basically a serial connection via IP. Only one client can be connected.
