### ISSUE TITLE
Vantage Vue Working

### ISSUE THREAD

**Issue by ebarretopr** [MarcoGos/davis_vantage#8]
I'm running version 1.1.0 and Vantage Vue is working without any issues. I just wish a faster update of data than 5 minutes.

**Comment by MarcoGos** [comment]
Thanks for reporting Vantage Vue is working. I don't however understand why updates take that long? What connection to your weather station/data logger are you using?

**Comment by ebarretopr** [comment]
Weatherlinkip

Edgardo

**Comment by MarcoGos** [comment]
Is the WeatherLink IP only used by the davis vantage integration or are other software solution also using the Weatherlink IP simultaneously?

**Comment by ebarretopr** [comment]
Only used by Home Assistant.

Edgardo Barreto
(787) 415-8191
