### ISSUE TITLE
Planned to add WeatherLink Live ?

### ISSUE THREAD

**Issue by S1M8N** [MarcoGos/davis_vantage#9]
Hey guys :)

For first, thank you a lot for your integration

I'm looking for a weatherlink live integration, are there any plans to make your integration compatible with weatherlink live ?

Thank you in advance for your next reply

**Comment by MarcoGos** [comment]
Hi, I'm not sure the Weatherlink Live has a local API which can be used, but I'm not planning to integrate that. Please take a look at the "Weatherlink Integration for Home Assistant" in HACS. It reads the data via the Cloud API. Maybe that can help.
